FROM python:3.6.3

# install environment deps
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends netcat \
  && apt-get -q clean

# set working dir
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
ADD ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

# add app
ADD . /usr/src/app

# run server
CMD ["./entrypoint-prod.sh"]
